spring.application.name=prueba-tecnica-leticia-andino
spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.sql
api.base-url=http://localhost:8080/api
api.base-web=http://localhost:8080
spring.web.cors.allow-credentials=true
Access-Control-Allow-Origin: http://localhost:8080
spring.web.cors.allowed-origins=http://localhost:8080
Access-Control-Allow-Methods: GET, POST, PUT, DELETE
spring.config.import=optional:file:.env[.properties]

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.com.prueba-tecnica-leticia-andino=DEBUG
logging.level.liquibase=DEBUG